var blogs = [
  {
    name: "Mayank Yadav",
    title: "Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur.",
    preview: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce sit amet elit ut justo interdum semper vitae vel nisi. Nam luctus, elit sit amet dictum semper, quam ante sollicitudin augue...",
    blog: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce sit amet elit ut justo interdum semper vitae vel nisi. Nam luctus, elit sit amet dictum semper, quam ante sollicitudin augue, vel cursus erat dolor vel turpis. Nam id ullamcorper sem, sit amet lobortis velit. In efficitur eleifend tortor. Nam a justo a turpis gravida lobortis. Proin rutrum libero mauris, eget tincidunt nibh aliquet sed. Nullam quis ipsum diam. Suspendisse blandit tincidunt sapien, ac congue neque. Aenean ac scelerisque leo. Maecenas ac augue magna. Proin dui lectus, pharetra quis libero vitae, pellentesque rutrum felis. Nam consectetur ornare odio, non maximus nisl imperdiet at. Praesent bibendum dui purus, vel venenatis diam finibus at. Lorem ipsum dolor sit amet, consectetur adipiscing elit.
    </p><p>
    Mauris posuere diam et nibh semper dapibus. Donec ut sapien nunc. Praesent feugiat odio quis turpis lacinia blandit. Curabitur lectus mauris, lacinia ac dui quis, dignissim cursus dolor. Pellentesque varius, nisi id facilisis pharetra, diam massa vulputate augue, id consequat tortor nunc sit amet lorem. Aliquam erat volutpat. Pellentesque nec mauris nisi.
    </p><p>
    Vivamus ex eros, pharetra rhoncus felis vel, lacinia facilisis nunc. Mauris aliquam commodo tellus. Etiam sit amet varius ipsum, quis maximus dolor. Etiam eu ante nunc. Mauris tincidunt nisi id nibh vehicula consequat id nec elit. Curabitur non nisi est. Praesent quis ipsum porta, eleifend dolor eu, maximus leo.
    </p><p>
    Duis blandit semper vestibulum. Etiam sed rhoncus nunc, a posuere ante. Suspendisse potenti. Donec eros mi, blandit id lorem a, mollis lobortis tortor. Suspendisse venenatis suscipit justo, blandit tempor ligula accumsan sit amet. Curabitur accumsan gravida dapibus. Maecenas gravida dapibus lacus in tempus. Integer neque mauris, consectetur eget consectetur maximus, mattis a dolor. Etiam eget vehicula est. Sed nec mi sit amet tortor ultricies molestie sed sed erat. In sagittis erat at dui malesuada, vitae sagittis mi imperdiet.
    </p><p>
    Nullam ut dui eget turpis facilisis pulvinar a sed lectus. Interdum et malesuada fames ac ante ipsum primis in faucibus. Nulla fermentum justo et sem semper, in euismod enim porttitor. Etiam ut elementum augue, facilisis ullamcorper urna. Aliquam nec metus turpis. Interdum et malesuada fames ac ante ipsum primis in faucibus. Nam id turpis urna. Sed pretium eleifend aliquam. Nulla tincidunt sollicitudin posuere.`
  },
  {
    name: "Ananya Neogi",
    title: "In ut velit vel libero elementum dictum. Duis vel ipsum laoreet, faucibus magna et.",
    preview: "Ut posuere magna non erat mattis ornare. Donec non faucibus neque. Maecenas ut sollicitudin tellus, sed suscipit odio. Praesent eleifend metus sem. Integer ultrices dolor turpis...",
    blog: `Ut posuere magna non erat mattis ornare. Donec non faucibus neque. Maecenas ut sollicitudin tellus, sed suscipit odio. Praesent eleifend metus sem. Integer ultrices dolor turpis, eget pretium enim varius vel. Donec sed imperdiet elit, et scelerisque mi. Nulla facilisi. Ut euismod lectus dui, ut tempus tortor mattis et. Suspendisse potenti. Vestibulum tempus nulla ante, vitae faucibus elit efficitur eget. Nullam id urna commodo, pharetra sapien sit amet, interdum ligula. Proin erat ex, fermentum at dictum a, porttitor eget lectus. Proin aliquet nisl nec commodo ornare. Aenean luctus lobortis mi, lobortis fermentum ipsum imperdiet eget. Morbi lacinia dictum magna, ornare bibendum nibh tincidunt vel.
    </p><p>
    Quisque eleifend tortor et urna finibus tincidunt. Sed tempor sed libero ac ullamcorper. Nam sed neque eget enim maximus congue a a arcu. Vivamus ut velit ligula. Pellentesque fringilla magna quis elit tempor dapibus. Cras luctus eget turpis sit amet vulputate. Curabitur congue erat erat, non viverra arcu posuere non. Nulla dapibus, mi a sodales vestibulum, magna nulla dictum ante, eu dignissim justo enim eget arcu. Morbi nec eros et lectus condimentum consectetur. Vestibulum eu eros ac metus congue pellentesque. Integer molestie egestas accumsan. Proin viverra gravida lorem in rutrum. Nam sodales vitae erat ac sollicitudin. Nullam imperdiet facilisis ipsum, in tempus erat aliquam eu.
    </p><p>
    Integer volutpat ex nec dui egestas commodo. Cras ut pellentesque dui, ac interdum magna. Donec augue erat, pulvinar eget lacus porttitor, efficitur condimentum risus. Ut scelerisque urna et justo eleifend volutpat. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Sed quis magna vel velit tempor lobortis eget nec nisl. Integer tempus metus velit. Quisque sed luctus nunc. Cras interdum arcu ipsum, id pellentesque metus rutrum et. Mauris eu vehicula nisl. Phasellus porttitor porta felis, at feugiat libero maximus eget. Donec consectetur, ligula ac lobortis commodo, ligula nibh pellentesque arcu, egestas mollis nibh nisi at justo. Proin accumsan nulla ligula, eu molestie arcu rutrum vel.
    </p><p>
    Morbi vel tincidunt tortor. Nunc sed euismod tortor. Quisque hendrerit nibh pulvinar, luctus nunc tempor, tempor dui. Quisque posuere mauris eu laoreet posuere. Nulla vitae fringilla mauris. Nullam lacus purus, gravida sed nulla non, ornare ullamcorper metus. Sed maximus efficitur posuere. Cras facilisis lorem nisl, eu pharetra augue dignissim sit amet. Cras fringilla sed tellus non vehicula.
    </p><p>
    Sed pretium nulla vitae purus accumsan, non dictum mauris convallis. Donec vitae lacus pellentesque, tempus velit non, luctus sem. Suspendisse elit elit, dictum eu dapibus eget, pretium vitae nisi. Vestibulum bibendum maximus facilisis. Duis id ullamcorper quam, nec posuere urna. Pellentesque auctor metus id ante luctus tincidunt. Duis at ex mollis, mollis elit ut, lacinia neque. Quisque consequat mi et quam interdum sodales in eu orci.`
  },
  {
    name: "Shreya Srivastav",
    title: "Fusce lectus odio, tincidunt sit amet dui vitae, euismod pretium lectus",
    preview: "Mauris imperdiet ipsum sed erat bibendum congue. Donec pellentesque vulputate erat, ut dictum nibh dignissim ut. Aliquam felis justo, auctor in quam id, ullamcorper mattis ex...",
    blog: `Mauris imperdiet ipsum sed erat bibendum congue. Donec pellentesque vulputate erat, ut dictum nibh dignissim ut. Aliquam felis justo, auctor in quam id, ullamcorper mattis ex. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean faucibus, diam hendrerit aliquam vestibulum, arcu diam ullamcorper augue, in rhoncus elit felis in lacus. Aliquam quis mi erat. Nunc feugiat aliquet maximus.
    </p><p>
    Quisque ultricies lorem sed semper vehicula. Duis odio dolor, tincidunt eu lacus rutrum, vestibulum blandit dui. Etiam eleifend iaculis tempor. Suspendisse potenti. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Mauris at diam est. Praesent commodo nisl sed elit bibendum, et sagittis felis tempus. Nam vestibulum volutpat malesuada. Integer consequat maximus mauris. Maecenas lobortis diam nisl, quis cursus neque vulputate eu. Vivamus ullamcorper augue massa, nec commodo nunc aliquam in. Cras tristique dictum lacinia.
    </p><p>
    Suspendisse pharetra tincidunt felis, in dapibus magna rhoncus in. Sed eget turpis magna. Aliquam cursus, nisl eu malesuada mattis, nisi lectus luctus augue, mattis interdum tellus sapien consequat eros. Praesent suscipit a orci non tristique. Nullam mattis lorem vitae elementum molestie. Duis semper ligula at dignissim vestibulum. In imperdiet purus lacus, vel venenatis purus porta vel. Nullam tincidunt metus feugiat, ultrices justo non, condimentum diam. In arcu ligula, sollicitudin sit amet diam sed, euismod auctor odio. Nam vitae efficitur nulla. Sed maximus, lacus vitae porta cursus, arcu nibh convallis arcu, in rutrum magna metus eget quam.
    </p><p>
    Etiam eu nunc at mi dapibus vehicula nec non ipsum. Proin quis accumsan magna, at consequat augue. Vivamus scelerisque egestas feugiat. Sed vehicula fringilla tortor eu porta. Pellentesque feugiat tincidunt libero id congue. Sed sollicitudin neque magna, viverra faucibus nulla scelerisque ac. Pellentesque in quam quam. Donec at lacus a erat tristique condimentum sed a felis. Etiam fermentum diam sit amet dui rutrum sagittis. Aliquam at tristique ipsum, id eleifend ex. Proin gravida, quam in consequat euismod, enim lorem bibendum ex, non aliquam lacus quam eu augue. Nam elementum, mauris quis lobortis rutrum, risus sem sagittis ante, pulvinar sollicitudin nulla felis sit amet nulla. Vivamus tincidunt vehicula tincidunt.
    </p><p>
    Integer varius lacus posuere urna sodales, vitae imperdiet risus feugiat. Maecenas quis neque id justo facilisis porta. In rutrum dui vel nibh laoreet blandit. Nunc sed justo justo. Nam condimentum cursus iaculis. Integer rutrum interdum mollis. Vestibulum quis augue vel nulla vestibulum dignissim quis nec ex. Aliquam ac tincidunt orci, vitae malesuada justo. Fusce at leo nec urna pellentesque hendrerit.`
  },
  {
    name: "Anuj Ladia",
    title: "Integer eget magna eu nunc placerat pharetra. Morbi gravida ornare eros",
    preview: "Quisque pharetra massa vitae magna rhoncus, sit amet pellentesque ante consequat. Proin convallis dapibus massa, quis consequat mi iaculis blandit. Nunc feugiat ac felis ac semper...",
    blog: `Quisque pharetra massa vitae magna rhoncus, sit amet pellentesque ante consequat. Proin convallis dapibus massa, quis consequat mi iaculis blandit. Nunc feugiat ac felis ac semper. Nullam fringilla, massa ultrices sodales blandit, purus felis sagittis justo, non sodales eros enim vitae leo. Nulla facilisi. Integer rhoncus est eu mauris mollis semper. Donec lobortis dignissim facilisis. Pellentesque eu aliquet neque. Donec massa ligula, tempus ac pretium ac, gravida vitae tellus. Donec sapien ligula, placerat ut accumsan ut, ultricies nec erat.
    </p><p>
    Interdum et malesuada fames ac ante ipsum primis in faucibus. Vivamus quis libero felis. Nam varius lacus enim, ac placerat est semper non. Cras sit amet libero dolor. Vivamus at posuere diam. Donec a lectus tincidunt lacus lobortis tincidunt. Phasellus dolor risus, tincidunt sed tincidunt ac, imperdiet ac sem. Etiam tincidunt lorem pulvinar, rutrum sem id, malesuada metus. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.
    </p><p>
    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean condimentum, risus at gravida egestas, tellus metus tincidunt metus, quis aliquet metus turpis sed tellus. Praesent aliquet nisl lectus, vitae scelerisque lacus auctor eu. Vestibulum gravida cursus venenatis. Proin dui sapien, bibendum condimentum consectetur ultrices, vestibulum non nisl. Etiam hendrerit nunc ut ligula aliquet commodo. Suspendisse sit amet risus eros. Donec tempus elementum odio, vel lobortis ex dignissim eu. Pellentesque eros nisl, placerat eget viverra vel, sollicitudin non arcu. Nullam nec tempor eros. Suspendisse libero felis, consectetur et tempor sed, viverra ornare tellus.
    </p><p>
    Duis sed est sit amet dolor ullamcorper pellentesque. Sed molestie id est ut euismod. Ut orci dui, cursus non fermentum at, rutrum ultrices diam. Aenean vitae facilisis massa. Cras pharetra velit a sem feugiat vestibulum. Maecenas vel dignissim erat. Phasellus suscipit augue lacus, id vulputate magna convallis et. Praesent facilisis bibendum felis vitae molestie.
    </p><p>
    Duis fermentum tincidunt ex eu efficitur. Vivamus semper odio nec porta posuere. Phasellus scelerisque eget quam in pretium. Suspendisse suscipit malesuada laoreet. Duis rutrum eros id ipsum rhoncus, sed feugiat turpis lobortis. Sed vestibulum sapien id massa accumsan pulvinar. Nulla vel ullamcorper sapien. Proin convallis dictum diam, sit amet luctus augue. Curabitur interdum egestas est, at ullamcorper diam facilisis sed. Donec quis pharetra lectus.`
  },
  {
    name: "Sonali Gupta",
    title: "Sed eget leo nec nunc imperdiet molestie. Nam dictum leo eget aliquet molestie.",
    preview: "Aenean quis dolor sit amet sapien pellentesque consequat vel sit amet lacus. Vivamus massa eros, semper porta posuere ut, gravida vitae sapien. Aenean ac enim purus...",
    blog: `Aenean quis dolor sit amet sapien pellentesque consequat vel sit amet lacus. Vivamus massa eros, semper porta posuere ut, gravida vitae sapien. Aenean ac enim purus. Integer felis neque, suscipit ultricies libero ac, bibendum fermentum tellus. Curabitur scelerisque aliquet ligula id iaculis. Maecenas id consectetur augue, eu faucibus ex. Maecenas ipsum nulla, sagittis nec mattis eu, ullamcorper id odio. Vivamus porta libero non odio condimentum tincidunt. Vestibulum vel sodales risus. Etiam orci ante, aliquam ac lectus eget, rutrum consequat elit. In hac habitasse platea dictumst. In hac habitasse platea dictumst. Nunc ac venenatis est. Pellentesque pharetra vitae lorem et feugiat. Fusce ut congue lacus. Etiam ut urna commodo erat pretium porttitor.
    </p><p>
    Suspendisse sodales varius ante quis hendrerit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas efficitur turpis et ligula commodo ultrices. Fusce suscipit odio in nunc iaculis rutrum. In finibus vel augue a placerat. Donec id magna nisl. Integer in tellus gravida, vehicula turpis ut, eleifend ante. Vivamus et elit turpis. Aenean ut ipsum at erat tincidunt blandit vel a enim. In hac habitasse platea dictumst. Maecenas aliquam varius auctor. Donec auctor nunc eget ex ullamcorper, et tempus mi suscipit. Praesent non egestas tortor. Pellentesque malesuada interdum purus, eget convallis sapien semper eu.
    </p><p>
    Praesent vulputate diam non fermentum mollis. Donec commodo neque vitae risus varius iaculis. Etiam vitae orci non ante varius fermentum quis sit amet lorem. Ut laoreet posuere est vitae placerat. Nunc tempus erat a dolor ornare, non malesuada tellus tempor. Proin consectetur nulla nunc, pharetra tempus enim porta a. Vestibulum convallis consequat libero vel viverra. Sed quis est a ligula volutpat ornare at et magna. Cras leo enim, dictum et consectetur eget, dictum vel magna. Vestibulum ac lorem in neque tristique suscipit nec quis elit. Quisque quis turpis consectetur, aliquet enim eu, elementum felis. Pellentesque nulla orci, euismod eget mattis a, vulputate ut ligula. Nunc dignissim elit ligula, vitae finibus erat sagittis ac. Morbi semper neque eu ligula interdum gravida. Nullam volutpat orci turpis, quis scelerisque felis sodales ut.
    </p><p>
    Pellentesque a posuere lectus. Nam ut purus eu felis porta congue. Duis lorem lectus, semper at porta a, maximus vel lacus. Nam posuere, metus eget molestie suscipit, arcu nulla tristique erat, id ullamcorper arcu sapien eget sem. Fusce porta ipsum justo, in tristique risus convallis ac. Aliquam nec orci eu metus dapibus varius non eu urna. Ut sed nunc nec sem ullamcorper aliquet in sit amet diam. Maecenas scelerisque mollis eleifend.
    </p><p>
    Etiam vehicula non mauris eu faucibus. Ut sollicitudin sodales hendrerit. Praesent mi augue, commodo vel libero sit amet, semper placerat purus. Nulla faucibus iaculis urna eget tincidunt. Pellentesque ut eros nec nisl tempus consequat lacinia vitae nulla. Etiam imperdiet mauris lacus, in dapibus mauris blandit ac. Suspendisse laoreet elit massa, vel varius neque efficitur nec. Duis vehicula viverra risus id aliquet. Duis vitae dignissim magna, vel ultrices metus. Sed eget leo nec nunc imperdiet molestie. Nam dictum leo eget aliquet molestie. Aliquam erat volutpat.`
  },
];